## Import the Libraries

In [1]:
import numpy as np 

## Generate a Random Dataset

In [4]:
df = np.random.randint(10,size=(5,5))

print(f"The dataset is :{df}")
print(f"The size of the dataset is :{df.shape}")

The dataset is :[[0 8 6 0 7]
 [7 0 1 1 0]
 [1 2 4 9 3]
 [9 3 7 7 9]
 [7 1 8 2 4]]
The size of the dataset is :(5, 5)


***Split the Dataset , the input will have the size of 5x4 and the output 5x1***

In [23]:
Input_data = df[:,:-1]
print(f"The Input dataset is :{Input_data}")
print(f"The size of Input data is : {Input_data.shape}")

print("------------------------------------------------------------------------")

Output_data = df[:,-1]
print(f"The Output dataset is :{Output_data}")
print(f"The size of Output data is : {Output_data.shape}")

The Input dataset is :[[0 8 6 0]
 [7 0 1 1]
 [1 2 4 9]
 [9 3 7 7]
 [7 1 8 2]]
The size of Input data is : (5, 4)
------------------------------------------------------------------------
The Output dataset is :[7 0 3 9 4]
The size of Output data is : 5


***Let assume that the NN will have 3 node in the hidden layers and 1 node in the output layers***

## Create the NN architecture 

In [61]:
def Neural_network(Input_data,hidden_nodes,Output_data):
    input_nodes = Input_data.shape[1]      # number of features in the dataset
    output_nodes = Output_data.shape[0]    #number of output in the dataset
    
    #Generate random weights matrix  that goes from the input to the hidden layer of size(hidden_node,Input_nodes)
    Weight_ih= np.round(np.random.uniform (-1,1,size=(input_nodes,hidden_nodes)),2)
    
    #Generate random weight matrix that goes from the hidden layer to the output layer of size(output_nodes,hidden_nodes)
    Weight_ho= np.round(np.random.uniform(-1,1,size=(output_nodes,hidden_nodes)),2)
    
    #Generate hidden bias
    bias_h = np.random.randint(2,size=(hidden_nodes,1))
    
    #Generate output bias
    bias_o= np.random.randint(2)
                               
    return Weight_ih,Weight_ho,bias_h,bias_o
                               

In [62]:
hidden_nodes = 3
Output_data = Output_data.reshape(-1, 5)

Weight_ih,Weight_ho,bias_h,bias_o = Neural_network(Input_data,hidden_nodes,Output_data)


In [63]:

print(f"The Weight_ih matrix :{Weight_ih}")
print(f"The size of Weight_ih is  : {Weight_ih.shape}")

print("------------------------------------------------------------------------")

print(f"The Weight_ho matrix :{Weight_ho}")
print(f"The size of Weight_ho is  : {Weight_ho.shape}")


print("------------------------------------------------------------------------")
print(f"The bias_h matrix :{bias_h}")
print(f"The size of bias_h is  : {bias_h.shape}")

print("------------------------------------------------------------------------")

print(f"The bias_o matrix :{bias_o}")



The Weight_ih matrix :[[-0.22 -0.17 -0.42]
 [-0.29 -0.03 -0.93]
 [-0.08  0.56  0.5 ]
 [ 0.74 -0.99  0.76]]
The size of Weight_ih is  : (4, 3)
------------------------------------------------------------------------
The Weight_ho matrix :[[0.51 0.41 0.55]]
The size of Weight_ho is  : (1, 3)
------------------------------------------------------------------------
The bias_h matrix :[[0]
 [0]
 [1]]
The size of bias_h is  : (3, 1)
------------------------------------------------------------------------
The bias_o matrix :0


## Train the Data

- **Feed-Forward Computation**
- **Back Propagation to Output layer**
- **Backpropagation to the hidden layer**
- **weight updates**

In [64]:
## sigmoid Activation Function

def sigmoid(Z): 
    return 1/(1 + np.exp(-Z))

In [82]:
def Forward_algo():
    
    Z_ih = np.zeros((Input_data.shape[0],hidden_nodes))
    
    counter=0
    col=0
    for X_train in Input_data :
        print(X_train)
        for i in Weight_ih.T:
            print(i)
            Z_ih[counter,col] = np.dot(X_train,i)
            col+=1
            print(Z_ih)
            print("--------------------------")
        col=0
        counter+=1
        
    

In [83]:
Forward_algo()

[0 8 6 0]
[-0.22 -0.29 -0.08  0.74]
[[-2.8  0.   0. ]
 [ 0.   0.   0. ]
 [ 0.   0.   0. ]
 [ 0.   0.   0. ]
 [ 0.   0.   0. ]]
--------------------------
[-0.17 -0.03  0.56 -0.99]
[[-2.8   3.12  0.  ]
 [ 0.    0.    0.  ]
 [ 0.    0.    0.  ]
 [ 0.    0.    0.  ]
 [ 0.    0.    0.  ]]
--------------------------
[-0.42 -0.93  0.5   0.76]
[[-2.8   3.12 -4.44]
 [ 0.    0.    0.  ]
 [ 0.    0.    0.  ]
 [ 0.    0.    0.  ]
 [ 0.    0.    0.  ]]
--------------------------
[7 0 1 1]
[-0.22 -0.29 -0.08  0.74]
[[-2.8   3.12 -4.44]
 [-0.88  0.    0.  ]
 [ 0.    0.    0.  ]
 [ 0.    0.    0.  ]
 [ 0.    0.    0.  ]]
--------------------------
[-0.17 -0.03  0.56 -0.99]
[[-2.8   3.12 -4.44]
 [-0.88 -1.62  0.  ]
 [ 0.    0.    0.  ]
 [ 0.    0.    0.  ]
 [ 0.    0.    0.  ]]
--------------------------
[-0.42 -0.93  0.5   0.76]
[[-2.8   3.12 -4.44]
 [-0.88 -1.62 -1.68]
 [ 0.    0.    0.  ]
 [ 0.    0.    0.  ]
 [ 0.    0.    0.  ]]
--------------------------
[1 2 4 9]
[-0.22 -0.29 -0.08  0.74]
[[-2.